[package]
name = "models"
version = "0.0.0"
edition = "2024"

[dependencies]
bitflags.workspace = true
chrono.workspace = true
config.workspace = true
diesel.workspace = true
diesel_migrations.workspace = true
errors.workspace = true
ipnetwork.workspace = true
macros.workspace = true
rand.workspace = true
serde.workspace = true
strum.workspace = true
ts-rs.workspace = true
utoipa.workspace = true
uuid.workspace = true

[dev-dependencies]
serial_test.workspace = true
