// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API Endpoints.
 */
export type Endpoints =
    | "/api/health"
    | "/api/ws"
    | "/api/auth/invite"
    | "/api/auth/register"
    | "/api/auth/login"
    | "/api/auth/logout"
    | "/api/auth/refresh"
    | "/api/auth/password-change"
    | "/api/auth/otp/validate"
    | "/api/auth/otp/disable"
    | "/api/auth/otp/validate"
    | "/api/auth/otp/backup-codes"
    | "/api/user"
    | "/api/session"
    | "/api/post";
