// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reasons for why fields are invalid.
 */
export type FieldErrorReason =
  | { "InvalidRange": { min: number; max: number } }
  | "InvalidCredentials"
  | "ExpiredInviteToken"
  | "InvalidInviteToken"
  | { "UserAlreadyExists": string };
