// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldErrorReason } from "./FieldErrorReason";

/**
 * A field error.
 */
export type FieldError = { field: string; reason: FieldErrorReason };
