// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserDTO } from "./UserDTO";

export type PostDTO = {
    id: string;
    title: string;
    content: string;
    author: UserDTO;
    updated_at: string;
    created_at: string;
};
