// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionInvalidationReason } from "./SessionInvalidationReason";
import type { UserDTO } from "./UserDTO";

export type SessionDTO = {
  id: string;
  user: UserDTO;
  session_token: string;
  access_token: string;
  user_agent: string;
  ip_address: string;
  valid: boolean;
  invalidated_at: string | null;
  invalidated_reason: SessionInvalidationReason | null;
  last_used: string;
  updated_at: string;
  created_at: string;
};
