// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldError } from "./FieldError";

/**
 * User errors.
 */
export type UserError =
  | { "BodyError": Array<FieldError> }
  | "TooManyOpenSessions"
  | { "Generic": string };
