// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserDTO = {
  id: string;
  name: string;
  otp_enabled: boolean;
  otp_validated: boolean;
  updated_at: string;
  created_at: string;
};
