// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * WebSocket Notifications.
 */
export type WsNotification =
    | "UpdatePosts"
    | {
          Ping: { message: string; data: string };
      };
