[package]
name = "errors"
version = "0.0.0"
edition = "2024"
license = "NONE"

[lib]
doctest = false

[dependencies]
axum.workspace = true
diesel.workspace = true
jsonwebtoken.workspace = true
serde.workspace = true
thiserror.workspace = true
ts-rs.workspace = true
utoipa.workspace = true
uuid.workspace = true
