services:
  nginx:
    container_name: wat-prod-nginx
    build:
      context: ../services/core/nginx
      dockerfile: Dockerfile
    volumes:
      - ../services/security/modsecurity/modsecurity.conf:/etc/modsecurity/modsecurity.conf
      - ../services/security/modsecurity/crs:/etc/modsecurity/crs
    env_file:
      - ./env/prod.env
    ports:
      - 80:80
      - 443:443
      - 3000:3000
      - 3001:3001
      - 3002:3002
    depends_on:
      anubis:
        condition: service_healthy
      client:
        condition: service_healthy
      server:
        condition: service_healthy
      grafana:
        condition: service_healthy
      pgweb:
        condition: service_healthy
      minio:
        condition: service_healthy

  nginx-metrics:
    container_name: wat-prod-nginx-metrics
    build:
      context: ../services/monitoring/nginx-metrics/
      dockerfile: Dockerfile
    depends_on:
      nginx:
        condition: service_healthy

  anubis:
    container_name: wat-prod-anubis
    build:
      context: ../services/security/anubis
      dockerfile: Dockerfile

  client:
    container_name: wat-prod-client
    build:
      context: ../services/core/client
      dockerfile: .docker/prod.Dockerfile
    env_file:
      - ./env/prod.env
    depends_on:
      server:
        condition: service_healthy

  server:
    container_name: wat-prod-server
    build:
      context: ../services/core/server
      dockerfile: .docker/prod.Dockerfile
    env_file:
      - ./env/prod.env
    depends_on:
      ai:
        condition: service_healthy
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  ai:
    container_name: wat-prod-ai
    build:
      context: ../services/core/ai
      dockerfile: .docker/prod.Dockerfile
    env_file:
      - ./env/prod.env
    depends_on:
      ollama:
        condition: service_healthy

  ollama:
    container_name: wat-prod-ollama
    build:
      context: ../services/core/ollama
      dockerfile: Dockerfile
    volumes:
      - prod_ollama_data:/root/.ollama
    tty: true

  postgres:
    container_name: wat-prod-postgres
    build:
      context: ../services/storage/postgres
      dockerfile: Dockerfile
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./env/prod.env

  pgweb:
    container_name: wat-prod-pgweb
    build:
      context: ../services/monitoring/pgweb
      dockerfile: Dockerfile
    env_file:
      - ./env/prod.env
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    container_name: wat-prod-redis
    build:
      context: ../services/storage/redis
      dockerfile: Dockerfile
    volumes:
      - prod_redis_data:/data
    env_file:
      - ./env/prod.env

  minio:
    container_name: wat-prod-minio
    build:
      context: ../services/storage/minio
      dockerfile: Dockerfile
    volumes:
      - prod_minio_data:/data
    env_file:
      - ./env/prod.env

  grafana:
    container_name: wat-prod-grafana
    build:
      context: ../services/monitoring/grafana
      dockerfile: Dockerfile
    volumes:
      - prod_grafana_data1:/var/lib/grafana
      - prod_grafana_data2:/etc/grafana/
    env_file:
      - ./env/prod.env
    depends_on:
      cadvisor:
        condition: service_healthy
      prometheus:
        condition: service_healthy
      promtail:
        condition: service_healthy
      pyroscope:
        condition: service_healthy

  loki:
    container_name: wat-prod-loki
    build:
      context: ../services/monitoring/loki
      dockerfile: Dockerfile
    volumes:
      - prod_loki_data:/etc/loki
    env_file:
      - ./env/prod.env

  promtail:
    container_name: wat-prod-promtail
    build:
      context: ../services/monitoring/promtail
      dockerfile: Dockerfile
    volumes:
      - /var/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./env/prod.env
    depends_on:
      loki:
        condition: service_healthy

  prometheus:
    container_name: wat-prod-prometheus
    build:
      context: ../services/monitoring/prometheus
      dockerfile: Dockerfile
    env_file:
      - ./env/prod.env

  cadvisor:
    container_name: wat-prod-cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    env_file:
      - ./env/prod.env

  pyroscope:
    container_name: wat-prod-pyroscope
    build:
      context: ../services/monitoring/pyroscope
      dockerfile: Dockerfile
    env_file:
      - ./env/prod.env

  autoheal:
    container_name: wat-prod-autoheal
    image: willfarrell/autoheal
    env_file:
      - ./env/prod.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  prod_grafana_data1: {}
  prod_grafana_data2: {}
  prod_loki_data: {}
  prod_minio_data: {}
  prod_ollama_data: {}
  prod_postgres_data: {}
  prod_redis_data: {}
