SecRuleEngine On
Include /etc/modsecurity/crs/crs-setup.conf
Include /etc/modsecurity/crs/rules/*.conf

# disable rule 949110 for anubis pass-challenge redirect
SecRule REQUEST_URI "@beginsWith /.within.website/x/cmd/anubis/api/pass-challenge" \
    "id:100001,phase:1,pass,nolog,ctl:ruleRemoveById=949110"
