apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki/
    jsonData:
      timeout: 60
      maxLines: 10000

  - name: Pyroscope
    type: grafana-pyroscope-datasource
    uid: pyroscope
    access: proxy
    url: http://pyroscope:4040
    jsonData:
      serverAddress: http://pyroscope:4040
      maxLines: 1000

  - name: Postgres
    type: postgres
    uid: postgres
    access: proxy
    url: postgres:5432
    user: root
    secureJsonData:
      password: "1UdEQQTMBGCCWxvY2FsaG9zdIcEfwAAATAdBgNVHQ4EFgQUgGAHp2OojO06lrYu"
    jsonData:
      connMaxLifetime: 14400
      database: root
      maxIdleConns: 1
      maxOpenConns: 5
      readTimeout: 30
      sslmode: disable
      writeTimeout: 30
