// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = "en";

export type Locales = "de" | "en";

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
    theme: {
        /**
         * L​i​g​h​t
         */
        light: string;
        /**
         * D​a​r​k
         */
        dark: string;
        /**
         * S​y​s​t​e​m
         */
        system: string;
    };
};

export type TranslationFunctions = {
    theme: {
        /**
         * Light
         */
        light: () => LocalizedString;
        /**
         * Dark
         */
        dark: () => LocalizedString;
        /**
         * System
         */
        system: () => LocalizedString;
    };
};

export type Formatters = {};
