services:
  # --------------------------------------------------------------------------
  # CORE
  # --------------------------------------------------------------------------

  ai:
    container_name: wat-dev-ai
    build:
      context: ../services/core/ai
      dockerfile: .docker/dev.Dockerfile
    env_file:
      - ./env/dev.env
    depends_on:
      ollama:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ../services/core/ai/.docker/dev.Dockerfile
        - action: rebuild
          path: ../services/core/ai/pyproject.toml
        - action: sync
          path: ../services/core/ai/
          target: /app/

  client:
    container_name: wat-dev-client
    build:
      context: ../services/core/client
      dockerfile: .docker/dev.Dockerfile
    env_file:
      - ./env/dev.env
    depends_on:
      server:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ../services/core/client/.docker/dev.Dockerfile
        - action: rebuild
          path: ../services/core/client/package.json
        - action: sync
          path: ../services/core/client/
          target: /app/

  nginx:
    container_name: wat-dev-nginx
    build:
      context: ../services/core/nginx
      dockerfile: Dockerfile
    volumes:
      - ../services/security/modsecurity/modsecurity.conf:/etc/modsecurity/modsecurity.conf
      - ../services/security/modsecurity/crs:/etc/modsecurity/crs
    env_file:
      - ./env/dev.env
    ports:
      - 80:80
      - 443:443
      - 3000:3000
      - 3001:3001
      - 3002:3002
    depends_on:
      anubis:
        condition: service_healthy
      server:
        condition: service_healthy
      client:
        condition: service_healthy
      grafana:
        condition: service_healthy
      pgweb:
        condition: service_healthy
      minio:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ../services/core/nginx/Dockerfile
        - action: rebuild
          path: ../services/core/nginx/nginx.conf
        - action: rebuild
          path: ../services/security/modsecurity/

  ollama:
    container_name: wat-dev-ollama
    build:
      context: ../services/core/ollama
      dockerfile: Dockerfile
    volumes:
      - dev_ollama_data:/root/.ollama
    tty: true

  server:
    container_name: wat-dev-server
    build:
      context: ../services/core/server
      dockerfile: .docker/dev.Dockerfile
    env_file:
      - ./env/dev.env
    depends_on:
      ai:
        condition: service_healthy
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      tempo:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ../services/core/server/.docker/dev.Dockerfile
        - action: rebuild
          path: ../services/core/server/Cargo.toml
        - action: sync
          path: ../services/core/server/
          target: /app/

  # --------------------------------------------------------------------------
  # MONITORING
  # --------------------------------------------------------------------------

  autoheal:
    container_name: wat-dev-autoheal
    image: willfarrell/autoheal
    env_file:
      - ./env/dev.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  cadvisor:
    container_name: wat-dev-cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/rootfs/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - ./env/dev.env

  grafana:
    container_name: wat-dev-grafana
    build:
      context: ../services/monitoring/grafana
      dockerfile: Dockerfile
    volumes:
      - dev_grafana_data1:/var/lib/grafana
      - dev_grafana_data2:/etc/grafana/
    env_file:
      - ./env/dev.env
    depends_on:
      cadvisor:
        condition: service_healthy
      loki:
        condition: service_healthy
      prometheus:
        condition: service_healthy
      promtail:
        condition: service_healthy
      pyroscope:
        condition: service_healthy
      tempo:
        condition: service_healthy
      postgres-metrics:
        condition: service_healthy
      redis-metrics:
        condition: service_healthy

  loki:
    container_name: wat-dev-loki
    build:
      context: ../services/monitoring/loki
      dockerfile: Dockerfile
    volumes:
      - dev_loki_data:/etc/loki
    env_file:
      - ./env/dev.env

  nginx-metrics:
    container_name: wat-dev-nginx-metrics
    build:
      context: ../services/monitoring/nginx-metrics/
      dockerfile: Dockerfile
    depends_on:
      nginx:
        condition: service_healthy

  pgweb:
    container_name: wat-dev-pgweb
    build:
      context: ../services/monitoring/pgweb
      dockerfile: Dockerfile
    env_file:
      - ./env/dev.env
    depends_on:
      postgres:
        condition: service_healthy

  postgres-metrics:
    container_name: wat-dev-postgres-metrics
    build:
      context: ../services/monitoring/postgres-metrics
    env_file:
      - ./env/dev.env
    depends_on:
      postgres:
        condition: service_healthy

  prometheus:
    container_name: wat-dev-prometheus
    build:
      context: ../services/monitoring/prometheus
      dockerfile: Dockerfile
    env_file:
      - ./env/dev.env

  promtail:
    container_name: wat-dev-promtail
    build:
      context: ../services/monitoring/promtail
      dockerfile: Dockerfile
    volumes:
      - /var/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./env/dev.env
    depends_on:
      loki:
        condition: service_healthy

  pyroscope:
    container_name: wat-dev-pyroscope
    build:
      context: ../services/monitoring/pyroscope
      dockerfile: Dockerfile
    env_file:
      - ./env/dev.env

  tempo:
    container_name: wat-dev-tempo
    build:
      context: ../services/monitoring/tempo
      dockerfile: Dockerfile
    volumes:
      - dev_tempo_data:/var/tempo
    env_file:
      - ./env/dev.env

  redis-metrics:
    container_name: wat-dev-redis-metrics
    build:
      context: ../services/monitoring/redis-metrics
    env_file:
      - ./env/dev.env
    environment:
      REDIS_ADDR: redis:6379
    depends_on:
      redis:
        condition: service_healthy

  # --------------------------------------------------------------------------
  # SECURITY
  # --------------------------------------------------------------------------

  anubis:
    container_name: wat-dev-anubis
    build:
      context: ../services/security/anubis
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ../services/security/anubis/Dockerfile
        - action: rebuild
          path: ../services/security/anubis/robots.txt
        - action: rebuild
          path: ../services/security/anubis/policy.yaml

  # --------------------------------------------------------------------------
  # STORAGE
  # --------------------------------------------------------------------------

  minio:
    container_name: wat-dev-minio
    build:
      context: ../services/storage/minio
      dockerfile: Dockerfile
    volumes:
      - dev_minio_data:/data
    env_file:
      - ./env/dev.env

  postgres:
    container_name: wat-dev-postgres
    build:
      context: ../services/storage/postgres
      dockerfile: Dockerfile
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./env/dev.env
    depends_on:
      minio:
        condition: service_healthy

  redis:
    container_name: wat-dev-redis
    build:
      context: ../services/storage/redis
      dockerfile: Dockerfile
    volumes:
      - dev_redis_data:/data
    env_file:
      - ./env/dev.env

volumes:
  dev_grafana_data1: {}
  dev_grafana_data2: {}
  dev_loki_data: {}
  dev_minio_data: {}
  dev_ollama_data: {}
  dev_postgres_data: {}
  dev_redis_data: {}
  dev_tempo_data: {}
