### Enable OTP (requires auth)

POST https://127.0.0.1/api/auth/otp/enable HTTP/1.1
Authorization: Bearer <access_token>

### Validate OTP (requires auth)

POST https://127.0.0.1/api/auth/otp/validate HTTP/1.1
Content-Type: application/json
Authorization: Bearer <access_token>

{
  "code": "<otp_code>"
}

### Disable OTP (requires auth)

POST https://127.0.0.1/api/auth/otp/disable HTTP/1.1
Content-Type: application/json
Authorization: Bearer <access_token>

{
  "code": "<otp_code>"
}

### Get OTP backup codes (requires auth)

POST https://127.0.0.1/api/auth/otp/backup-codes HTTP/1.1
Content-Type: application/json
Authorization: Bearer <access_token>

{
  "code": "<otp_code>"
}
