on:
  workflow_dispatch:
  pull_request:
  #push:
  #branches:
  #- master

name: CI

jobs:
  ci:
    name: CI
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Setup LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "17.0"

      - name: Setup Cargo Binary Install
        uses: cargo-bins/cargo-binstall@main

      - name: Install Cargo Dependencies
        run: |
          cargo binstall cargo-deny diesel_cli --no-confirm --disable-telemetry

      - name: Install Other Dependencies
        run: |
          sudo sed -i '/^deb .* main/ s/main/main universe/' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install libtinfo6 mold python3-poetry

      - name: Run Checks
        run: |
          ./cli.sh check

      - name: Format Codebase
        run: |
          ./cli.sh format

      - name: Commit Formatting
        run: |
          git config --global user.name 'CI'
          git config --global user.email 'ci@github.com'
          git diff-index --quiet HEAD || git commit -am "ci: format codebase"
          git pull --rebase
          git push
