[package]
name = "server"
version = "0.0.0"
edition = "2024"
build = "build/build.rs"

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false

[profile.release]
codegen-units = 1
debug = true
lto = "fat"
opt-level = 3
panic = "abort"

[profile.dev]
debug = true
lto = "off"
opt-level = 0

[profile.dev.package."*"]
opt-level = 3

[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.dependencies]
auth = { path = "crates/auth" }
config = { path = "crates/config" }
crypto = { path = "crates/crypto" }
errors = { path = "crates/errors" }
macros = { path = "crates/macros" }
models = { path = "crates/models" }
sample = { path = "crates/sample" }

afl = "=0.17.1"
aliri_braid = "=0.4.0"
arbitrary = "=1.4.2"
argon2 = "=0.5.3"
axum = { version = "=0.8.8", features = ["macros", "ws"] }
axum-extra = { version = "=0.12.5", features = ["typed-header"] }
axum-prometheus = "=0.10.0"
axum-test = "=18.4.0"
base64 = "=0.22.1"
bitflags = "=2.11.0"
chrono = { version = "=0.4.44", features = ["serde"] }
criterion = { version = "=0.8.2", features = ["html_reports"] }
darling = "=0.23.0"
derive_more = { version = "=2.1.1", features = ["full"] }
diesel = { version = "=2.3.6", features = [
    "chrono",
    "postgres",
    "r2d2",
    "uuid",
    "serde_json",
    "network-address",
] }
diesel_migrations = { version = "=2.3.1", features = ["postgres"] }
dotenvy = "=0.15.7"
fake = { version = "=4.4.0", features = ["derive", "chrono", "uuid"] }
flux-rs = { git = "https://github.com/flux-rs/flux.git" }
http = "=1.4.0"
http-body-util = "=0.1.3"
ipnetwork = { version = "=0.21.1", features = ["serde"] }
itertools = "=0.14.0"
jsonwebtoken = "=9.3.0"
kani = { git = "https://github.com/model-checking/kani" }
lazy_static = "=1.5.0"
maud = { version = "=0.27.0", features = ["axum"] }
metrics = "=0.24.3"
mockall = "=0.14.0"
openssl-probe = "=0.2.1"
opentelemetry = "=0.31.0"
pretty_assertions = "=1.4.1"
proc-macro-crate = "=3.4.0"
proc-macro2 = "=1.0.106"
proptest = "=1.10.0"
pyroscope = "=0.5.8"
pyroscope_pprofrs = "=0.2.10"
quote = "=1.0.44"
rand = "=0.10.0"
rand_core = "=0.10.0"
rayon = "=1.11.0"
reqwest = { version = "0.13.2", features = ["json"] }
rstest = "=0.26.1"
serde = { version = "=1.0.221", features = ["derive"] }
serde-binary = "=0.5.0"
serde_json = "=1.0.145"
serial_test = "=3.3.1"
strum = { version = "=0.28.0", features = ["derive", "strum_macros"] }
strum_macros = "=0.28.0"
syn = "=2.0.117"
tera = "=1.20.1"
thiserror = "=2.0.18"
tokio = { version = "=1.49.0", features = ["full"] }
tokio-cron-scheduler = "=0.15.1"
tower-http = { version = "=0.6.8", features = ["full"] }
tracing = "=0.1.44"
tracing-opentelemetry = "=0.32.1"
tracing-subscriber = { version = "=0.3.22", features = ["env-filter", "json"] }
opentelemetry_sdk = { version = "=0.31.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "=0.31.0", features = ["grpc-tonic"] }
opentelemetry-semantic-conventions = "=0.31.0"
ts-rs = { version = "=11.0.1", features = [
    "format",
    "uuid-impl",
    "heapless-impl",
    "chrono-impl",
] }
utoipa = { version = "=5.4.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "=9.0.2", features = ["axum"] }
utoipauto = "=0.2.0"
uuid = { version = "=1.21.0", features = ["serde", "v4"] }

[dependencies]
auth.workspace = true
config.workspace = true
crypto.workspace = true
errors.workspace = true
macros.workspace = true
models.workspace = true
sample.workspace = true

axum-extra.workspace = true
axum-prometheus.workspace = true
axum.workspace = true
chrono.workspace = true
dotenvy.workspace = true
http-body-util.workspace = true
http.workspace = true
ipnetwork.workspace = true
maud.workspace = true
metrics.workspace = true
openssl-probe.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry-semantic-conventions.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
pyroscope.workspace = true
pyroscope_pprofrs.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
tera.workspace = true
tokio-cron-scheduler.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
ts-rs.workspace = true
utoipa-swagger-ui.workspace = true
utoipa.workspace = true
utoipauto.workspace = true
uuid.workspace = true

[dev-dependencies]
axum-test.workspace = true
criterion.workspace = true
fake.workspace = true
pretty_assertions.workspace = true
proptest.workspace = true
rstest.workspace = true
serial_test.workspace = true
